group 'com.tuntori.mighty_ble'
version '1.0'

apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    namespace 'com.tuntori.mighty_ble'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdkVersion 24
    }
}