group 'com.aeologic.adhoc.qr_utils'
version '1.0-SNAPSHOT'

apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    namespace 'com.aeologic.adhoc.qr_utils'
    defaultConfig {
        minSdkVersion 24
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'com.karumi:dexter:5.0.0'
    implementation 'me.dm7.barcodescanner:zxing:1.9.13'
}